server:
  port: 80
  servlet:
    context-path: /Techstore
spring:
  datasource:
    password: Nhat12072002
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: kcme hhsx clkl deri
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: "minhnhatnguyenphan1207@gmail.com\t"
 
    